# Generated by Django 2.0.3 on 2018-03-25 12:15

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalKind',
            new_name='Species',
        ),
    ]
