# Generated by Django 2.0.3 on 2018-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_auto_20180325_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
            preserve_default=False,
        ),
    ]
