# Generated by Django 2.0.3 on 2018-03-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_citizen_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='fandom_url',
            field=models.URLField(default='http://zootopia.wikia.com/wiki/List_of_Species_Seen_in_Zootopia', max_length=400),
            preserve_default=False,
        ),
    ]
