# Generated by Django 2.0.3 on 2018-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='danger_level',
            field=models.CharField(choices=[('safe', 'safe'), ('minor', 'minor'), ('considerable', 'considerable'), ('high', 'high'), ('very_high', 'very_high')], default='safe', max_length=12),
            preserve_default=False,
        ),
    ]
